<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Zubr</title>

<!-- CSS -->
<link rel='stylesheet' type='text/css' href='/javascripts/tabs/jquery-ui-1.8.7.custom.css' media='screen' />
<link href="/admin/style/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
<!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="admin/style/css/ie6.css" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->

<!-- JavaScripts-->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type='text/javascript' src='/javascripts/tabs/jquery-ui-1.8.7.custom.min.js' ></script>
<script type='text/javascript' src='/javascripts/tabs/admin_tab.js' ></script>
<script type="text/javascript" src="/admin/javascript/_tags.js"></script>


<script type="text/javascript" src="/admin/javascript/_universities.js"></script>
<script type="text/javascript" src="/admin/javascript/_slides.js"></script>
<script type="text/javascript" src="/admin/javascript/_locations.js"></script>
<script type="text/javascript" src="/admin/javascript/_users.js"></script>
<script type="text/javascript" src="/admin/javascript/_scholarships.js"></script>
<script type="text/javascript" src="/admin/javascript/_studyareas.js"></script>
<script type="text/javascript" src="/admin/javascript/_degrees.js"></script>
<script type="text/javascript" src="/admin/javascript/_universities_relations.js"></script>
<script type="text/javascript" src="/admin/javascript/_specialities.js"></script>
<script type="text/javascript" src="/admin/javascript/_questions.js"></script>
<script type="text/javascript" src="/admin/javascript/_promotion.js"></script>
<script type="text/javascript" src="/javascripts/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="/admin/javascript/_news.js"></script>
<script type="text/javascript" src="/admin/javascript/_jobpostings.js"></script>
<script type="text/javascript" src="/admin/javascript/_subscriptions.js"></script>
<script type="text/javascript" src="/admin/javascript/_answers.js"></script>
<script type="text/javascript" src="/admin/javascript/_organizations.js"></script>
<script type="text/javascript" src="/admin/javascript/_tests.js"></script>
<script type="text/javascript" src="/admin/javascript/_testquestions.js"></script>




</head>
