<div class="section">

                    <div class="section-title">Нас поддержали</div>

                    <div class="section-content">

                        <ul class="nice-list">
                            <li><a href="http://www.backnet.kz">British Alumni Club KZ</a></li>
                            <li><a href="http://www.dostik.kz">ОЦ "Достык"</a></li>
                            <li><a href="http://www.purdue.edu">Purdue University Alumni KZ</a></li>
                            <li><a href="/help/promo/" class="more">Поддержать проект &#187;</a></li>
                        </ul>
                        
                    </div>

                </div>