<script type="text/javascript"><!--
reformal_wdg_w    = "713";
reformal_wdg_h    = "460";
reformal_wdg_domain    = "zubbr";
reformal_wdg_mode    = 0;
reformal_wdg_title   = "Zubbr.kz";
reformal_wdg_ltitle  = "Оставьте свой отзыв";
reformal_wdg_lfont   = "";
reformal_wdg_lsize   = "";
reformal_wdg_color   = "#39cc3e";
reformal_wdg_bcolor  = "#3f4543";
reformal_wdg_tcolor  = "#ffffff";
reformal_wdg_align   = "left";
reformal_wdg_charset = "utf-8";
reformal_wdg_waction = 0;
reformal_wdg_vcolor  = "#345678";
reformal_wdg_cmline  = "#E0E0E0";
reformal_wdg_glcolor  = "#345678";
reformal_wdg_tbcolor  = "#FFFFFF";
reformal_wdg_tcolor_aw4  = "#3F4543";
 
reformal_wdg_bimage = "http://www.zubbr.kz/images/complaint.png";
 //-->
</script>

<script type="text/javascript" language="JavaScript" src="http://widget.reformal.ru/tabn2v4.js"></script><noscript><a href="http://zubbr.reformal.ru">Zubbr.kz feedback</a> <a href="http://reformal.ru">на платформе <img src="http://widget.reformal.ru/i/reformal_ru.png" alt="Reformal"/></a></noscript>