<!-- Start CountZero code  -->
<script type="text/javascript"><!--
cz_user=44885;cz_type=1;cz_str="&wd="+screen.width;
cz_str+="&hg="+screen.height+"&du="+escape(document.URL);
cz_str+="&rf="+escape(document.referrer);
cz_str="<a href='http://zero.kz/?u="+cz_user+"' target='_blank'>"+
"<img src='http://zero.kz/c.php?u="+cz_user+"&t="+cz_type+cz_str+"'"+
" border='0px' width='88' height='31' alt='CountZero' /><\/a>";
document.write(cz_str);//--></script><noscript>
<a href='http://zero.kz/?u=44885' target='_blank'>
<img src='http://zero.kz/c.php?u=44885' border='0px' width='88'
height='31' alt='CountZero' /></a></noscript>
<!-- End CountZero code  -->