<div id="dashboard">
    <div class="column left" id="column-1">
        <div class="column-content">
            <div class="column-title">О проекте Zubbr.kz</div>
            <p>Все, что Вы хотели знать о нас. Если это не все, то спрашивайте</p>
            <a href="/help/about/">Изучить &#187;</a>
        </div>
    </div>
    <div class="column left" id="column-2">
        <div class="column-content">
            <div class="column-title">Следуйте за нами</div>
            <ul class="plain-list">
                <li><a href="http://www.facebook.com/pages/Zubbrkz-%D0%B2%D1%81%D0%B5-%D0%BE-%D0%B7%D0%B0%D1%80%D1%83%D0%B1%D0%B5%D0%B6%D0%BD%D0%BE%D0%BC-%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8/162881643764361?sk=wall">На Фейсбуке</a></li>
                <li><a href="http://twitter.com/zubbrkz/">В Твиттере</a></li>
                <li><a href="http://vkontakte.ru/public24776912" >Вконтакте</a></li>
                <li><a href="http://my.mail.ru/mail/zubbrkz" >В Моем Мире</a></li>
            </ul>
        </div>
    </div>
    <div class="column left" id="column-3">
                <div class="column-content">
                    <div class="column-title">Помощь &amp; Поддержка</div>
                    <p>Что-то не получается? Попробуйте найти ответ в этом разделе.</p>
                    <a href="/help/about/#faq">Часто задаваемы вопросы &#187;</a>
                </div>
            </div>

            <div class="column right" id="column-4">
                <div class="column-content">
                    <div class="column-title">На связи</div>
                    <p>Тел: +7 701 723 90 83<br/>Email: info@zubbr.kz</p>
                    <a href="javascript:MyOtziv.mo_show_box();">Форма обратной связи &#187;</a>
                </div>
            </div>
    <div class="clearer">&nbsp;</div>
</div>

<div id="footer">
    <div class="left">&copy; <?php echo '2010 - ' . date('Y') ?> http://www.zubbr.kz <span class="text-separator">&rarr;</span> <a href="/">В Зуббр</a> <span class="text-separator">|</span><a href="/test/">Тесты</a> <span class="text-separator">|</span> <a href="/uni/">ВУЗы</a> <span class="text-separator">|</span> <a href="/users/">Пипл</a> <span class="text-separator">|</span> <a href="/questions/">Вопрос/Ответ</a></div>
    <div class="right"><a href="http://templates.arcsin.se/">Шаблон</a> создан в <a href="http://arcsin.se/">Arcsin</a></div>
    <div class="clearer">&nbsp;</div>
</div>
<div id="stat_counters">
    <div class="right">
    
    <p>
                <?php require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_1inkz.inc";?>
                <?php require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_liveinternet.inc";?>
                <?php require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_zero.inc";?>
                <?php require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_resurskz.inc";?>
                <?php require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_yandex_me.inc";?>
                <?php require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_internetskz.inc";?>
            </p>
    
    </div>
    <div class="clearer">&nbsp;</div>
</div>
</div>
</div>


<?php
    
    require_once $_SERVER['DOCUMENT_ROOT'] . "/include/_reformal.inc";
?>
    
             
</body>
</html>