	<div class="right sidebar-reg" id="sidebar-2">
				<div class="section">
					<div class="section-title">Что требуется для регистрации?</div>
					<div class="section-content">
						<ul class="nice-list">
							<li><span class="quiet">1.</span> Уделить 3 минуты времени</li>
							<li><span class="quiet">2.</span> Внести регистрационные данные</li>
							<li><span class="quiet">3.</span> Запонить профайл пользователя</li>
						</ul>
					</div>
				</div>
				<div class="section">
					<div class="section-title">Что дает мне регистрация?</div>
					<div class="section-content">
						<ul class="nice-list">
							<li><span class="quiet">a.</span> Прохождение тестов для подготовки к ЕНТ</li>
							<li><span class="quiet">b.</span> Ведение статистики собственного прогресса</li>
							<li><span class="quiet">c.</span> Участие в дисскуссиях на разные темы</li>
							<li><span class="quiet">d.</span> Возможность задать вопросы представилям ВУЗ-ов</li>
							<li><span class="quiet">e.</span> Получить консультацию преподавателей</li>
						</ul>
					</div>
				</div>

				<div class="section network-section">
					<div class="section-title">Что ещё интересного?</div>
					<div class="section-content">
						<ul class="nice-list">
							<li>Ищите единомышленников в своем городе</li>
							<li>Излагайте своё мнение в микроблогах</li>
							<li>Получайте призы за высокие результаты</li>
							<li>Участвуйте в создании разделов проекта (wiki)</li>
							<li>Делитесь впечатлениями</li>
							<li>Познавайте! Развивайтесь! Учитесь!</li>
						</ul>
					</div>
				</div>
	</div>