    <div class="right sidebar-reg" id="sidebar-2">
                <div class="section">
                    <div class="section-title">
                    <div class="left">Как не забывать пароль?</div>
                    <div class="right"><img src="/images/icon-time.gif" width="14" height="14" alt="" /></div>
                        <div class="clearer">&nbsp;</div>
                    </div>
                    <div class="section-content">
                        <ul class="nice-list">
                            <ul class="nice-list">
                            <li><span class="quiet">1.</span> Использовать парольные фразы</li>
                            <li><span class="quiet">2.</span> Писать английскими буквами русские слова (слово = ckjdj)</li>
                            <li><span class="quiet">3.</span> 3amenyat нек0т0рые 6уkвы похо}|{uмu</li>
                            <li><span class="quiet">4.</span> Использовать менеджеры паролей</li>
                            <li><span class="quiet">5.</span> Придумать свою систему (первые три буквы названия сайта + еще что то)</li>
                        </ul>
                    </div>
                </div>
    </div>